language: ruby
rvm:
  - 2.5.8
cache:
  - bundler
services:
  - postgresql
before_script:
  — bundle exec bundle install --jobs=3 --retry=3
script:
  - export RAILS_ENV=test
  — bundle exec rake db:create db:schema:load db:test:prepare
